### PR TITLE
Added popup instructions

### PR DESCRIPTION
**Pull request by blusoulna**

### CODE REVIEW

**Comment by blusoulna** [comment]
Resolving issue #5

**Comment by mohitkharb** [comment]
@blusoulna did you push your changes to this branch?

**Review by mohitkharb — APPROVED** [review]
approved

**Comment by mohitkharb** [comment]
@hangal : this is the final PR for UI changes, can you please review.

**Review by hangal — COMMENTED** [review]
not sure why data files are being merged in this PR if it's for popup hover?

**Comment by mohitkharb** [comment]
the data updates are for storing alliance names in the datasets.

**Comment by blusoulna** [comment]
Updated the following:
1. Info icon on search only shows up when typing something
2. Added an info icon for aggregate summary text
3. If the values on filter are default, no extra aggregate summary is shown

**Comment by mohitkharb** [comment]
merging the final updates to the branch.

**Pull request merged**
